services:
  db:
    image: postgres:14
    container_name: db_postgres_students_ci_cd
    restart: always
    ports:
      - 4000:5432
    env_file:
      - .env
    volumes:
      - pg_students:/var/lib/pgsql/data

  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pg_students:
